# Generated by Django 2.0.7 on 2018-07-28 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='placeholder.jpg', upload_to='img'),
            preserve_default=False,
        ),
    ]
