# Generated by Django 2.0.7 on 2018-07-29 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='writer',
            field=models.CharField(default='John H. Watson', max_length=255),
            preserve_default=False,
        ),
    ]
